package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/renanmav/GoExpert-CleanArch/internal/infra/graphql/generated"
	"github.com/renanmav/GoExpert-CleanArch/internal/infra/graphql/model"
	"github.com/renanmav/GoExpert-CleanArch/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	dto := usecase.CreateOrderInput{
		Price: input.Price,
		Tax:   input.Tax,
	}

	order, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}

	return &model.Order{
		ID:         order.ID,
		Price:      order.Price,
		Tax:        order.Tax,
		FinalPrice: order.FinalPrice,
	}, nil
}

// ReadAllOrders is the resolver for the readAllOrders field.
func (r *queryResolver) ReadAllOrders(ctx context.Context) ([]*model.Order, error) {
	output, err := r.ReadAllOrdersUseCase.Execute()
	if err != nil {
		return nil, err
	}

	var ordersModel []*model.Order
	for _, order := range output.Orders {
		ordersModel = append(ordersModel, &model.Order{
			ID:         order.ID,
			Price:      order.Price,
			Tax:        order.Tax,
			FinalPrice: order.FinalPrice,
		})
	}

	return ordersModel, nil
}

// ReadOrderByID is the resolver for the readOrderById field.
func (r *queryResolver) ReadOrderByID(ctx context.Context, id string) (*model.Order, error) {
	dto := usecase.ReadOrderByIdInput{
		ID: id,
	}

	order, err := r.ReadOrderByIdUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}

	return &model.Order{
		ID:         order.ID,
		Price:      order.Price,
		Tax:        order.Tax,
		FinalPrice: order.FinalPrice,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
